sourcery:
  # Exclude only the tests folder and setup.py; docs/ is included for review
  exclude:
    - tests/
    - setup.py

  # Enable or disable specific refactoring rules
  rules:
    use-namedtuple: true
    merge-nested-ifs: true
    assign-if-exp: true
    inline-immediately-returned-variable: false
    remove-redundant-else: true

  # Only show suggestions with at least this confidence (0.0 - 1.0)
  min-confidence: 0.7

  # Restrict Sourcery to these branches (modify as needed)
  enabled-branches:
    - main
    - develop

  # Post suggestions as pull request comments
  pr-comments: true

  # For more options, see: https://docs.sourcery.ai/docs/configuration/