# Trojan Application Configuration
# This file demonstrates YAML configuration format

# Application settings
app:
  name: "Trojan Application"
  version: "1.0.0"
  environment: "development"
  debug: true
  port: 3000

# Database configuration
database:
  host: "localhost"
  port: 5432
  name: "trojan_db"
  username: "trojan_user"
  password: "default_password"
  ssl: false
  pool:
    min: 2
    max: 10
    idle_timeout: 30000

# Logging configuration
logging:
  level: "info"
  file: "./logs/app.log"
  max_size: "10MB"
  max_files: 5

# External services
services:
  redis:
    host: "localhost"
    port: 6379
    password: null
  
  api:
    base_url: "https://api.example.com"
    timeout: 5000
    retry_attempts: 3

# Feature flags
features:
  enable_caching: true
  enable_metrics: false
  enable_auth: true